name: Docker Compose Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-docker-compose@v1

      - name: Build and Deploy
        run: |
          docker-compose up --build -d
