name: Deploy to DEV

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64, dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        run: |
          rm .env
          rm docker-compose.yml
          cp /home/ubuntu/Desktop/.env.prod .env
          cp .env web/.env
          cp -r /home/ubuntu/Desktop/tdev/actions-runner/_work/Albanian-ASR/Albanian-ASR /home/ubuntu/Desktop/actions-runner/unedua/Albanian-ASR/Albanian-ASR
          mv /home/ubuntu/Desktop/tdev/actions-runner/unedua/Albanian-ASR/Albanian-ASR /home/ubuntu/Desktop/actions-runner/unedua/Albanian-ASR/dev

          mv Albanian-ASR dev

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/Desktop/dev/actions-runner/unedua/Albanian-ASR/Albanian-ASR
          sudo docker-compose up --build -d
