name: Deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt update
          sudo apt install docker-compose

      - name: Configure environment
        run: |
          cp ${{ secrets.envFileLocation }} .env
          sudo chmod 600 .env

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/Desktop/actions-runner/unedua/Albanian-ASR/Albanian-ASR
          yes | sudo apt install ffmpeg
          sudo docker-compose --env-file .env up --build -d
