name: Deploy to DEV

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64, dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        run: |
          rm .env
          rm -rf dev
          cp /home/ubuntu/Desktop/.env.prod .env
          cp /home/ubuntu/Desktop/.env.dev_web web/.env
          cp -rp /home/ubuntu/Desktop/dev/actions-runner/_work/Albanian-ASR/Albanian-ASR /home/ubuntu/Desktop/actions-runner/unedua/Albanian-ASR/Albanian-ASR/dev
      - name: Build and Deploy
        run: |
          cd /home/ubuntu/Desktop/dev/actions-runner/unedua/Albanian-ASR/Albanian-ASR
          sudo docker-compose up --build -d
