name: Deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        run: |
          rm .env
          rm docker-compose.yml
          cp /home/ubuntu/Desktop/.env.prod .env
          cp /home/ubuntu/Desktop/.env.prod_web web/.env
          mv docker-compose.prod.yml docker-compose.yml
          cp -r /home/ubuntu/Desktop/dev/actions-runner/_work/Albanian-ASR/Albanian-ASR /home/ubuntu/Desktop/actions-runner/unedua/Albanian-ASR/Albanian-ASR/
          mv /home/ubuntu/Desktop/actions-runner/unedua/Albanian-ASR/Albanian-ASR/Albanian-ASR /home/ubuntu/Desktop/actions-runner/unedua/Albanian-ASR/Albanian-ASR/dev
      - name: Build and Deploy
        run: |
          cd /home/ubuntu/Desktop/actions-runner/unedua/Albanian-ASR/Albanian-ASR
          sudo docker-compose up --build -d
