name: Deploy

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        run: |
          cp "$ENV_FILE_LOCATION" .env
          sudo chmod 600 .env
        env:
          ENV_FILE_LOCATION: ${{ secrets.ENVFILELOCATION }}

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/Desktop/actions-runner/unedua/Albanian-ASR/Albanian-ASR
          yes | sudo apt install ffmpeg
          sudo docker-compose --env-file .env up --build -d
