name: Deploy to DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, linux, X64, dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        run: |
          sudo cp /home/ubuntu/safe/.env.prod .env
          sudo cp /home/ubuntu/safe/.env.prod web/.env
          [ -d "/home/ubuntu/prod/actions-runner/production/Albanian-ASR/Albanian-ASR/dev" ] && sudo rm -r /home/ubuntu/prod/actions-runner/production/Albanian-ASR/Albanian-ASR/dev
          sudo cp -r /home/ubuntu/dev/actions-runner/developement/Albanian-ASR/Albanian-ASR /home/ubuntu/prod/actions-runner/production/Albanian-ASR/Albanian-ASR/
          sudo sudo mv /home/ubuntu/prod/actions-runner/production/Albanian-ASR/Albanian-ASR/Albanian-ASR /home/ubuntu/prod/actions-runner/production/Albanian-ASR/Albanian-ASR/dev

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/prod/actions-runner/production/Albanian-ASR/Albanian-ASR
          sudo chown -R $USER:$USER /home/ubuntu/prod/actions-runner/production/Albanian-ASR/Albanian-ASR
          sudo docker-compose up --build -d
